# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Create R cache directories (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir -p ~/Library/Caches/org.R-project.R/R/renv/binary/macos/R-4.5/aarch64-apple-darwin20/repository
          chmod -R 755 ~/Library/Caches/org.R-project.R

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
 
      - name: Install rcmdcheck
        shell: Rscript {0}
        run: renv::install("rcmdcheck")

      - name: Install remotes
        shell: Rscript {0}
        run: renv::install("remotes")

      - uses: r-lib/actions/check-r-package@v2
        with: 
          error-on: '"error"'


    



