# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:

name: build-ss-R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          #- {os: ubuntu-latest,   r: 'release'}
          #- {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: engineerd/configurator@v0.0.9
        if: matrix.config.os == 'windows-latest'
        with: 
          name: "ss_win.exe"
          fromGitHubReleases: "true"
          repo: "nmfs-stock-synthesis/stock-synthesis"
          urlTemplate: "https://github.com/nmfs-stock-synthesis/stock-synthesis/releases/download/{{version}}/ss_win.exe"
          version: "latest"
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: move SS3 in windows to expected location
        if: matrix.config.os == 'windows-latest'
        run: |
          ls "$GITHUB_ENV"
          mv ss_win.exe ss.exe
          cp ss.exe inst/extdata/ss.exe
          rm ss_win.exe

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::remotes
      
      - name: Get the latest SS3 executable for linux and move to expected location
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          curl https://api.github.com/repos/nmfs-stock-synthesis/stock-synthesis/releases/latest | grep "browser_download_url" | grep -Eo 'https://[^\"]*' | grep "ss_linux" | xargs wget
          mv ss_linux ss
          sudo chmod a+x ss
          cp ss inst/extdata/ss
          rm ss
      
      - name: Get the latest SS3 executable for macOS and move to expected location
        if: matrix.config.os == 'macOS-latest' 
        run:  |
          curl https://api.github.com/repos/nmfs-stock-synthesis/stock-synthesis/releases/latest | grep "browser_download_url" | grep -Eo 'https://[^\"]*' | grep "ss_osx" | xargs wget
          mv ss_osx ss
          sudo chmod a+x ss
          cp ss inst/extdata/ss
          rm ss



      - uses: r-lib/actions/check-r-package@v2
        with: 
          error-on: '"error"'

      - name: remove ss executable
        run: rm inst/extdata/ss


    



